name: programow_flutter_getx_boilerplate
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^3.2.2
  meta: ^1.1.8
  http: ^0.12.1
  slimy_card: ^1.0.4

  our_cl:
    git: https://github.com/LeydenJar/our_component_library.git

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  our_cl:
    path: ../our_component_library

flutter:
  uses-material-design: true

assets:
  - assets
